# Generated by Django 6.0 on 2026-01-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0004_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financetracker.category'),
        ),
    ]
